name: GitHub Actions Demo
on: [push]
jobs:
  Deploy-Server:
    runs-on: ubuntu-latest
    name: Deploying server on heroku
    steps:
      - uses: actions/checkout@v3
      - run: cd backend
      - run: ls
