name: Deployment to Heroku
on:
  pull_request:
    branches:
      - master
jobs:
  Deploy-Server:
    runs-on: ubuntu-latest
    name: Deploying server on heroku
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "reminder-at-location-server"
          heroku_email: "eduanirud@gmail.com"
          appdir: "backend"
